import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import {Header} from "./components/header";
import { library } from '@fortawesome/fontawesome-svg-core'
import { fas } from "@fortawesome/free-solid-svg-icons";

library.add(fas)

const poppins = Poppins({weight: ['100','200','300','400','500','600','700','800','900'],subsets: ['latin-ext']} );

export const metadata: Metadata = {
  title: "Igreja Unasp SP",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        {children}
        </body>
    </html>
  );
}
